package io.github.stronghorse44.tunnels.dns

enum class TrackerKind(val label: String) {
    ADS("ads"),
    ANALYTICS("analytics"),
    ATTRIBUTION("attribution"),
    CRASH("crash reporting"),
    PUSH("push"),
    TELEMETRY("telemetry"),
    SOCIAL("social"),
}

/**
 * One tracking endpoint. [exactHost] entries name a host (and its subdomains) under a domain that is
 * otherwise innocent, like `graph.facebook.com`; the rest name a whole registrable domain.
 */
data class TrackerDomain(val domain: String, val kind: TrackerKind, val vendor: String, val exactHost: Boolean = false)

/**
 * Well-known tracking, advertising, attribution, crash-reporting and telemetry domains, curated by hand.
 * Matching is by exact host (or a subdomain of it) first, then by registrable domain.
 */
object TrackerDomains {
    private fun r(domain: String, kind: TrackerKind, vendor: String) = TrackerDomain(domain, kind, vendor)
    private fun h(host: String, kind: TrackerKind, vendor: String) = TrackerDomain(host, kind, vendor, exactHost = true)

    val all: List<TrackerDomain> = listOf(
        // Google
        r("google-analytics.com", TrackerKind.ANALYTICS, "Google"),
        r("googletagmanager.com", TrackerKind.ANALYTICS, "Google"),
        r("googletagservices.com", TrackerKind.ADS, "Google"),
        r("googlesyndication.com", TrackerKind.ADS, "Google"),
        r("googleadservices.com", TrackerKind.ADS, "Google"),
        r("doubleclick.net", TrackerKind.ADS, "Google"),
        r("admob.com", TrackerKind.ADS, "Google"),
        r("2mdn.net", TrackerKind.ADS, "Google"),
        r("googleoptimize.com", TrackerKind.ANALYTICS, "Google"),
        r("app-measurement.com", TrackerKind.ANALYTICS, "Google Firebase"),
        r("crashlytics.com", TrackerKind.CRASH, "Google Firebase"),
        h("firebaseinstallations.googleapis.com", TrackerKind.ANALYTICS, "Google Firebase"),
        h("firebaseremoteconfig.googleapis.com", TrackerKind.TELEMETRY, "Google Firebase"),
        h("firebaselogging-pa.googleapis.com", TrackerKind.TELEMETRY, "Google Firebase"),
        h("firebaselogging.googleapis.com", TrackerKind.TELEMETRY, "Google Firebase"),
        h("firebaseperusertopics-pa.googleapis.com", TrackerKind.ANALYTICS, "Google Firebase"),
        h("adservice.google.com", TrackerKind.ADS, "Google"),
        h("analytics.google.com", TrackerKind.ANALYTICS, "Google"),
        h("ads.google.com", TrackerKind.ADS, "Google"),
        h("ade.googlesyndication.com", TrackerKind.ADS, "Google"),
        // Meta
        r("facebook.net", TrackerKind.SOCIAL, "Meta"),
        h("graph.facebook.com", TrackerKind.SOCIAL, "Meta"),
        h("an.facebook.com", TrackerKind.ADS, "Meta Audience Network"),
        h("pixel.facebook.com", TrackerKind.ANALYTICS, "Meta"),
        // Amazon
        r("amazon-adsystem.com", TrackerKind.ADS, "Amazon"),
        h("device-metrics-us.amazon.com", TrackerKind.TELEMETRY, "Amazon"),
        h("device-metrics-us-2.amazon.com", TrackerKind.TELEMETRY, "Amazon"),
        h("fls-na.amazon.com", TrackerKind.ANALYTICS, "Amazon"),
        h("unagi.amazon.com", TrackerKind.ANALYTICS, "Amazon"),
        // Microsoft
        h("dc.services.visualstudio.com", TrackerKind.TELEMETRY, "Microsoft App Insights"),
        r("appcenter.ms", TrackerKind.CRASH, "Microsoft App Center"),
        r("clarity.ms", TrackerKind.ANALYTICS, "Microsoft Clarity"),
        h("vortex.data.microsoft.com", TrackerKind.TELEMETRY, "Microsoft"),
        h("self.events.data.microsoft.com", TrackerKind.TELEMETRY, "Microsoft"),
        h("mobile.events.data.microsoft.com", TrackerKind.TELEMETRY, "Microsoft"),
        h("browser.events.data.microsoft.com", TrackerKind.TELEMETRY, "Microsoft"),
        h("events.data.microsoft.com", TrackerKind.TELEMETRY, "Microsoft"),
        h("ads.microsoft.com", TrackerKind.ADS, "Microsoft"),
        h("bat.bing.com", TrackerKind.ADS, "Microsoft"),
        // Attribution and deep linking
        r("appsflyer.com", TrackerKind.ATTRIBUTION, "AppsFlyer"),
        r("appsflyersdk.com", TrackerKind.ATTRIBUTION, "AppsFlyer"),
        r("adjust.com", TrackerKind.ATTRIBUTION, "Adjust"),
        r("adjust.io", TrackerKind.ATTRIBUTION, "Adjust"),
        r("adjust.world", TrackerKind.ATTRIBUTION, "Adjust"),
        r("adj.st", TrackerKind.ATTRIBUTION, "Adjust"),
        r("go.link", TrackerKind.ATTRIBUTION, "Adjust"),
        r("branch.io", TrackerKind.ATTRIBUTION, "Branch"),
        r("app.link", TrackerKind.ATTRIBUTION, "Branch"),
        r("bnc.lt", TrackerKind.ATTRIBUTION, "Branch"),
        r("kochava.com", TrackerKind.ATTRIBUTION, "Kochava"),
        r("singular.net", TrackerKind.ATTRIBUTION, "Singular"),
        r("sng.link", TrackerKind.ATTRIBUTION, "Singular"),
        r("apsalar.com", TrackerKind.ATTRIBUTION, "Singular"),
        r("tenjin.io", TrackerKind.ATTRIBUTION, "Tenjin"),
        r("tenjin.com", TrackerKind.ATTRIBUTION, "Tenjin"),
        r("airbridge.io", TrackerKind.ATTRIBUTION, "Airbridge"),
        r("abr.ge", TrackerKind.ATTRIBUTION, "Airbridge"),
        r("tune.com", TrackerKind.ATTRIBUTION, "TUNE"),
        r("measurementapi.com", TrackerKind.ATTRIBUTION, "TUNE"),
        r("mobileapptracking.com", TrackerKind.ATTRIBUTION, "TUNE"),
        r("hasoffers.com", TrackerKind.ATTRIBUTION, "TUNE"),
        h("appmetrica.yandex.net", TrackerKind.ANALYTICS, "Yandex AppMetrica"),
        h("appmetrica.yandex.com", TrackerKind.ANALYTICS, "Yandex AppMetrica"),
        h("mc.yandex.ru", TrackerKind.ANALYTICS, "Yandex Metrica"),
        h("an.yandex.ru", TrackerKind.ADS, "Yandex"),
        // Product analytics and engagement
        r("amplitude.com", TrackerKind.ANALYTICS, "Amplitude"),
        r("mixpanel.com", TrackerKind.ANALYTICS, "Mixpanel"),
        r("segment.io", TrackerKind.ANALYTICS, "Segment"),
        r("segment.com", TrackerKind.ANALYTICS, "Segment"),
        r("heapanalytics.com", TrackerKind.ANALYTICS, "Heap"),
        r("flurry.com", TrackerKind.ANALYTICS, "Flurry"),
        r("count.ly", TrackerKind.ANALYTICS, "Countly"),
        r("mparticle.com", TrackerKind.ANALYTICS, "mParticle"),
        r("localytics.com", TrackerKind.ANALYTICS, "Localytics"),
        r("leanplum.com", TrackerKind.ANALYTICS, "Leanplum"),
        r("clevertap.com", TrackerKind.ANALYTICS, "CleverTap"),
        r("wzrkt.com", TrackerKind.ANALYTICS, "CleverTap"),
        r("moengage.com", TrackerKind.ANALYTICS, "MoEngage"),
        r("braze.com", TrackerKind.ANALYTICS, "Braze"),
        r("braze.eu", TrackerKind.ANALYTICS, "Braze"),
        r("appboy.com", TrackerKind.ANALYTICS, "Braze"),
        r("customer.io", TrackerKind.ANALYTICS, "Customer.io"),
        r("iterable.com", TrackerKind.ANALYTICS, "Iterable"),
        r("pendo.io", TrackerKind.ANALYTICS, "Pendo"),
        r("fullstory.com", TrackerKind.ANALYTICS, "FullStory"),
        r("hotjar.com", TrackerKind.ANALYTICS, "Hotjar"),
        r("hotjar.io", TrackerKind.ANALYTICS, "Hotjar"),
        r("smartlook.com", TrackerKind.ANALYTICS, "Smartlook"),
        r("smartlook.cloud", TrackerKind.ANALYTICS, "Smartlook"),
        r("uxcam.com", TrackerKind.ANALYTICS, "UXCam"),
        r("logrocket.com", TrackerKind.ANALYTICS, "LogRocket"),
        r("lr-ingest.io", TrackerKind.ANALYTICS, "LogRocket"),
        r("lr-in.com", TrackerKind.ANALYTICS, "LogRocket"),
        r("mouseflow.com", TrackerKind.ANALYTICS, "Mouseflow"),
        r("crazyegg.com", TrackerKind.ANALYTICS, "Crazy Egg"),
        r("contentsquare.net", TrackerKind.ANALYTICS, "Contentsquare"),
        r("clicktale.net", TrackerKind.ANALYTICS, "Contentsquare"),
        r("quantummetric.com", TrackerKind.ANALYTICS, "Quantum Metric"),
        r("glassboxdigital.io", TrackerKind.ANALYTICS, "Glassbox"),
        r("matomo.cloud", TrackerKind.ANALYTICS, "Matomo"),
        r("piwik.pro", TrackerKind.ANALYTICS, "Piwik PRO"),
        r("snowplowanalytics.com", TrackerKind.ANALYTICS, "Snowplow"),
        r("kissmetrics.com", TrackerKind.ANALYTICS, "Kissmetrics"),
        r("kissmetrics.io", TrackerKind.ANALYTICS, "Kissmetrics"),
        r("woopra.com", TrackerKind.ANALYTICS, "Woopra"),
        r("getclicky.com", TrackerKind.ANALYTICS, "Clicky"),
        r("statcounter.com", TrackerKind.ANALYTICS, "StatCounter"),
        r("chartbeat.com", TrackerKind.ANALYTICS, "Chartbeat"),
        r("chartbeat.net", TrackerKind.ANALYTICS, "Chartbeat"),
        r("parsely.com", TrackerKind.ANALYTICS, "Parse.ly"),
        r("cloudflareinsights.com", TrackerKind.ANALYTICS, "Cloudflare Web Analytics"),
        r("plausible.io", TrackerKind.ANALYTICS, "Plausible"),
        r("optimizely.com", TrackerKind.ANALYTICS, "Optimizely"),
        r("launchdarkly.com", TrackerKind.TELEMETRY, "LaunchDarkly"),
        r("split.io", TrackerKind.TELEMETRY, "Split"),
        r("apptimize.com", TrackerKind.ANALYTICS, "Apptimize"),
        r("taplytics.com", TrackerKind.ANALYTICS, "Taplytics"),
        r("swrve.com", TrackerKind.ANALYTICS, "Swrve"),
        r("exponea.com", TrackerKind.ANALYTICS, "Bloomreach"),
        r("emarsys.net", TrackerKind.ANALYTICS, "Emarsys"),
        r("sailthru.com", TrackerKind.ANALYTICS, "Sailthru"),
        r("marketo.net", TrackerKind.ANALYTICS, "Marketo"),
        r("mktoresp.com", TrackerKind.ANALYTICS, "Marketo"),
        r("pardot.com", TrackerKind.ANALYTICS, "Salesforce Pardot"),
        h("track.hubspot.com", TrackerKind.ANALYTICS, "HubSpot"),
        r("hs-analytics.net", TrackerKind.ANALYTICS, "HubSpot"),
        r("hsadspixel.net", TrackerKind.ADS, "HubSpot"),
        r("intercom.io", TrackerKind.ANALYTICS, "Intercom"),
        // Performance monitoring and crash reporting
        r("sentry.io", TrackerKind.CRASH, "Sentry"),
        r("bugsnag.com", TrackerKind.CRASH, "Bugsnag"),
        r("raygun.io", TrackerKind.CRASH, "Raygun"),
        r("raygun.com", TrackerKind.CRASH, "Raygun"),
        r("rollbar.com", TrackerKind.CRASH, "Rollbar"),
        r("instabug.com", TrackerKind.CRASH, "Instabug"),
        r("bugfender.com", TrackerKind.CRASH, "Bugfender"),
        r("embrace.io", TrackerKind.CRASH, "Embrace"),
        r("newrelic.com", TrackerKind.TELEMETRY, "New Relic"),
        r("nr-data.net", TrackerKind.TELEMETRY, "New Relic"),
        r("datadoghq.com", TrackerKind.TELEMETRY, "Datadog"),
        r("datadoghq.eu", TrackerKind.TELEMETRY, "Datadog"),
        r("browser-intake-datadoghq.com", TrackerKind.TELEMETRY, "Datadog"),
        r("dynatrace.com", TrackerKind.TELEMETRY, "Dynatrace"),
        r("instana.io", TrackerKind.TELEMETRY, "Instana"),
        r("appdynamics.com", TrackerKind.TELEMETRY, "AppDynamics"),
        r("eum-appdynamics.com", TrackerKind.TELEMETRY, "AppDynamics"),
        // Push
        r("onesignal.com", TrackerKind.PUSH, "OneSignal"),
        r("pushwoosh.com", TrackerKind.PUSH, "Pushwoosh"),
        r("urbanairship.com", TrackerKind.PUSH, "Airship"),
        r("batch.com", TrackerKind.PUSH, "Batch"),
        r("wonderpush.com", TrackerKind.PUSH, "WonderPush"),
        r("kumulos.com", TrackerKind.PUSH, "Kumulos"),
        // Mobile ad networks and mediation
        h("unityads.unity3d.com", TrackerKind.ADS, "Unity Ads"),
        h("config.unityads.unity3d.com", TrackerKind.ADS, "Unity Ads"),
        r("applovin.com", TrackerKind.ADS, "AppLovin"),
        r("applvn.com", TrackerKind.ADS, "AppLovin"),
        r("adcolony.com", TrackerKind.ADS, "AdColony"),
        r("chartboost.com", TrackerKind.ADS, "Chartboost"),
        r("vungle.com", TrackerKind.ADS, "Vungle"),
        r("liftoff.io", TrackerKind.ADS, "Liftoff"),
        r("ironsrc.com", TrackerKind.ADS, "ironSource"),
        r("ironsrc.mobi", TrackerKind.ADS, "ironSource"),
        r("supersonicads.com", TrackerKind.ADS, "ironSource"),
        r("inmobi.com", TrackerKind.ADS, "InMobi"),
        r("inmobicdn.net", TrackerKind.ADS, "InMobi"),
        r("mopub.com", TrackerKind.ADS, "MoPub"),
        r("smaato.net", TrackerKind.ADS, "Smaato"),
        r("smaato.com", TrackerKind.ADS, "Smaato"),
        r("pubmatic.com", TrackerKind.ADS, "PubMatic"),
        r("rubiconproject.com", TrackerKind.ADS, "Magnite"),
        r("openx.net", TrackerKind.ADS, "OpenX"),
        r("criteo.com", TrackerKind.ADS, "Criteo"),
        r("criteo.net", TrackerKind.ADS, "Criteo"),
        r("taboola.com", TrackerKind.ADS, "Taboola"),
        r("outbrain.com", TrackerKind.ADS, "Outbrain"),
        r("adnxs.com", TrackerKind.ADS, "Xandr"),
        r("appnexus.com", TrackerKind.ADS, "Xandr"),
        r("moatads.com", TrackerKind.ADS, "Oracle Moat"),
        r("doubleverify.com", TrackerKind.ADS, "DoubleVerify"),
        r("adsafeprotected.com", TrackerKind.ADS, "Integral Ad Science"),
        r("scorecardresearch.com", TrackerKind.ANALYTICS, "Comscore"),
        r("comscore.com", TrackerKind.ANALYTICS, "Comscore"),
        r("imrworldwide.com", TrackerKind.ANALYTICS, "Nielsen"),
        r("quantserve.com", TrackerKind.ADS, "Quantcast"),
        r("quantcount.com", TrackerKind.ADS, "Quantcast"),
        r("bluekai.com", TrackerKind.ADS, "Oracle BlueKai"),
        r("demdex.net", TrackerKind.ADS, "Adobe Audience Manager"),
        r("omtrdc.net", TrackerKind.ANALYTICS, "Adobe Analytics"),
        r("adobedtm.com", TrackerKind.ANALYTICS, "Adobe"),
        r("2o7.net", TrackerKind.ANALYTICS, "Adobe Analytics"),
        r("everesttech.net", TrackerKind.ADS, "Adobe Advertising"),
        r("krxd.net", TrackerKind.ADS, "Salesforce DMP"),
        r("exelator.com", TrackerKind.ADS, "Nielsen eXelate"),
        r("rlcdn.com", TrackerKind.ADS, "LiveRamp"),
        r("liadm.com", TrackerKind.ADS, "LiveIntent"),
        r("agkn.com", TrackerKind.ADS, "Neustar"),
        r("adsrvr.org", TrackerKind.ADS, "The Trade Desk"),
        r("casalemedia.com", TrackerKind.ADS, "Index Exchange"),
        r("indexww.com", TrackerKind.ADS, "Index Exchange"),
        r("bidswitch.net", TrackerKind.ADS, "BidSwitch"),
        r("sharethrough.com", TrackerKind.ADS, "Sharethrough"),
        r("teads.tv", TrackerKind.ADS, "Teads"),
        r("yieldmo.com", TrackerKind.ADS, "Yieldmo"),
        r("mgid.com", TrackerKind.ADS, "MGID"),
        r("revcontent.com", TrackerKind.ADS, "Revcontent"),
        r("zemanta.com", TrackerKind.ADS, "Zemanta"),
        r("media.net", TrackerKind.ADS, "Media.net"),
        r("serving-sys.com", TrackerKind.ADS, "Sizmek"),
        r("flashtalking.com", TrackerKind.ADS, "Flashtalking"),
        r("innovid.com", TrackerKind.ADS, "Innovid"),
        r("spotxchange.com", TrackerKind.ADS, "SpotX"),
        r("spotx.tv", TrackerKind.ADS, "SpotX"),
        r("advertising.com", TrackerKind.ADS, "Yahoo"),
        r("adtechus.com", TrackerKind.ADS, "Yahoo"),
        h("ads.yahoo.com", TrackerKind.ADS, "Yahoo"),
        h("analytics.yahoo.com", TrackerKind.ANALYTICS, "Yahoo"),
        r("mydas.mobi", TrackerKind.ADS, "Yahoo"),
        r("nexage.com", TrackerKind.ADS, "Yahoo"),
        r("aerserv.com", TrackerKind.ADS, "InMobi"),
        r("fyber.com", TrackerKind.ADS, "Fyber"),
        r("inner-active.mobi", TrackerKind.ADS, "Fyber"),
        r("pangle.io", TrackerKind.ADS, "Pangle"),
        r("pangleglobal.com", TrackerKind.ADS, "Pangle"),
        r("byteoversea.com", TrackerKind.TELEMETRY, "ByteDance"),
        r("mintegral.com", TrackerKind.ADS, "Mintegral"),
        r("mintegral.net", TrackerKind.ADS, "Mintegral"),
        r("rayjump.com", TrackerKind.ADS, "Mintegral"),
        r("bidmachine.io", TrackerKind.ADS, "BidMachine"),
        r("hyprmx.com", TrackerKind.ADS, "HyprMX"),
        r("pubnative.net", TrackerKind.ADS, "Verve"),
        r("ogury.com", TrackerKind.ADS, "Ogury"),
        r("ogury.io", TrackerKind.ADS, "Ogury"),
        r("presage.io", TrackerKind.ADS, "Ogury"),
        r("adikteev.com", TrackerKind.ADS, "Adikteev"),
        r("remerge.io", TrackerKind.ADS, "Remerge"),
        r("molocoads.com", TrackerKind.ADS, "Moloco"),
        r("startapp.com", TrackerKind.ADS, "Start.io"),
        r("tapjoy.com", TrackerKind.ADS, "Tapjoy"),
        r("zedo.com", TrackerKind.ADS, "Zedo"),
        r("yieldlab.net", TrackerKind.ADS, "Yieldlab"),
        r("adform.net", TrackerKind.ADS, "Adform"),
        r("adform.com", TrackerKind.ADS, "Adform"),
        r("smartadserver.com", TrackerKind.ADS, "Equativ"),
        r("sascdn.com", TrackerKind.ADS, "Equativ"),
        r("360yield.com", TrackerKind.ADS, "Improve Digital"),
        r("stickyadstv.com", TrackerKind.ADS, "FreeWheel"),
        r("tapad.com", TrackerKind.ADS, "Tapad"),
        r("mathtag.com", TrackerKind.ADS, "MediaMath"),
        r("mediamath.com", TrackerKind.ADS, "MediaMath"),
        r("simpli.fi", TrackerKind.ADS, "Simpli.fi"),
        r("gumgum.com", TrackerKind.ADS, "GumGum"),
        r("undertone.com", TrackerKind.ADS, "Undertone"),
        r("conversantmedia.com", TrackerKind.ADS, "Conversant"),
        r("dotomi.com", TrackerKind.ADS, "Conversant"),
        r("eyeota.net", TrackerKind.ADS, "Eyeota"),
        r("lotame.com", TrackerKind.ADS, "Lotame"),
        r("crwdcntrl.net", TrackerKind.ADS, "Lotame"),
        r("owneriq.net", TrackerKind.ADS, "OwnerIQ"),
        r("samsungads.com", TrackerKind.ADS, "Samsung"),
        r("samsungacr.com", TrackerKind.TELEMETRY, "Samsung"),
        // Platform telemetry
        h("telemetry.mozilla.org", TrackerKind.TELEMETRY, "Mozilla"),
        h("events.mapbox.com", TrackerKind.TELEMETRY, "Mapbox"),
        h("metrics.data.hicloud.com", TrackerKind.TELEMETRY, "Huawei"),
        h("tracking.miui.com", TrackerKind.TELEMETRY, "Xiaomi"),
        h("data.mistat.xiaomi.com", TrackerKind.TELEMETRY, "Xiaomi"),
        h("data.mistat.intl.xiaomi.com", TrackerKind.TELEMETRY, "Xiaomi"),
        // Social platforms' ad and analytics hosts
        h("ads.twitter.com", TrackerKind.ADS, "X"),
        h("ads-api.twitter.com", TrackerKind.ADS, "X"),
        h("analytics.twitter.com", TrackerKind.ANALYTICS, "X"),
        h("ads.linkedin.com", TrackerKind.ADS, "LinkedIn"),
        h("ads.pinterest.com", TrackerKind.ADS, "Pinterest"),
        h("ct.pinterest.com", TrackerKind.ANALYTICS, "Pinterest"),
        h("tr.snapchat.com", TrackerKind.ANALYTICS, "Snap"),
        h("ads.reddit.com", TrackerKind.ADS, "Reddit"),
        h("alb.reddit.com", TrackerKind.ANALYTICS, "Reddit"),
        h("events.reddit.com", TrackerKind.ANALYTICS, "Reddit"),
    )

    private val byRegistrable: Map<String, TrackerDomain> = all.filter { !it.exactHost }.associateBy { it.domain }
    private val byHost: Map<String, TrackerDomain> = all.filter { it.exactHost }.associateBy { it.domain }

    /** The entry [host] belongs to, or null. Exact-host entries win over registrable ones. */
    fun match(host: String): TrackerDomain? {
        val h = PublicSuffix.normalize(host)
        if (h.isEmpty()) return null
        var start = 0
        while (true) {
            byHost[h.substring(start)]?.let { return it }
            val dot = h.indexOf('.', start)
            if (dot < 0) break
            start = dot + 1
        }
        return byRegistrable[PublicSuffix.registrableDomain(h)]
    }

    fun isTracker(host: String): Boolean = match(host) != null

    fun byDomain(domain: String): TrackerDomain? = byHost[domain] ?: byRegistrable[domain]
}
